package com.thinh.snaplet.utils.network

enum class ApiErrorCode {
    INVALID_CREDENTIALS,
    LIMIT_DEVICE,
    ACCOUNT_LOCKED,
    POST_CREATE_LIMIT_EXCEEDED,
    RELATIONSHIP_LIMIT_EXCEEDED,
    EMAIL_REGISTERED_WITH_GOOGLE
}